name: employee_directory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_easyloading: 3.0.0
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.1
  path_provider: ^2.0.5
  path: ^1.8.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.4
  moor_generator: any

flutter: 
  uses-material-design: true

